using MVC_Vidily.Models;
using System;
using System.CodeDom;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace MVC_Vidily.ViewModel
{
    public class MovieFormViewModel
    {
        public IEnumerable<Genre> Genres { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
        public int? Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }


        [Display(Name="Genre")]
        [Required]
        public byte? GenreId { get; set; }//Foreign Key

        [Column(TypeName = "Date")]// Change DateTime type to Date.
        [Display(Name = "Date Released")]
        [Required]
        public DateTime? ReleaseDate { get; set; }

        [Display(Name = "Number In Stock")]
        [Range(1, 20)]
        [Required]
        public byte? NumInStock { get; set; }
 
        public string Title
        {
            get
            {
                return Id != 0 ? "Edit Movie" : "New Movie";
            }
        }


        //Constructor To Initailize initail state 
        public MovieFormViewModel()
        {
            Id = 0;
        }
        public MovieFormViewModel(Movie movie)
        {
            Id = movie.Id;
             Name = movie.Name;
             ReleaseDate = movie.ReleaseDate;
             NumInStock = movie.NumInStock;
             GenreId = movie.GenreId;

        }
    }
}
