// <auto-generated />
namespace MVC_Vidily.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MoiveNumInStockRange1to20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoiveNumInStockRange1to20));
        
        string IMigrationMetadata.Id
        {
            get { return "202010190850401_MoiveNumInStockRange1to20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
