// <auto-generated />
namespace MVC_Vidily.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataContext_UserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataContext_UserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202010131505191_DataContext_UserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
