using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Vidily.Models
{
    public class MembershipType
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
        public byte Id { get; set; }
      
        public short SignUpFee { get; set; }
        public byte DurationInMonths { get; set; }

        //Section 3 Exercise 1 
        
        public string MembershipTypeName { get; set; }

        public byte DiscountRate { get; set; }
    }
}