using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Policy;
using System.Security.Principal;
using System.Web;

namespace MVC_Vidily.Models
{
    public class Movie
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        
        [Display(Name="Genre")]
   
        public Genre Genre { get; set; }//Navigation Property to Movies to Genre Table 


        [Required]
        public byte GenreId { get; set; }//Foreign Key


        [Column(TypeName = "Date")]// Change DateTime type to Date.
        [Display(Name = "Date Added")]
    
        public DateTime DateAdded { get; set; }


        [Column(TypeName = "Date")]// Change DateTime type to Date.
        [Display(Name = "Date Released")]
  
        public DateTime ReleaseDate { get; set; }

        [Display(Name="Number In Stock")]
        [Range(1,20)]    
        public byte NumInStock { get; set; }
    }
}