using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Policy;
using System.Security.Principal;
using System.Web;

namespace MVC_Vidily.Models
{
    public class Movie
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
        public int Id { get; set; }
        public string Name { get; set; }

        [Required]
        public Genre Genre { get; set; }//Navigation Property to Movies to Genre Table 
        public byte GenreId { get; set; }//Foreign Key

        [Column(TypeName = "Date")]// Change DateTime type to Date.
        public DateTime DateAdded { get; set; }


        [Column(TypeName = "Date")]// Change DateTime type to Date.
        public DateTime ReleaseDate { get; set; }
        public int NumInStock { get; set; }
    }
}